# Exercise 2

------------------------------------------------------------------------

### **2.2.1:**

The size (slope) of the relationship between count of maternal DNMs and Maternal age is 0.37757. This means that for every additional year of maternal age we'd expect an additional 0.37757 DNMs. This seems to generally match the scatter plot, as the slope is positive, and less than 1.

------------------------------------------------------------------------

### **2.2.2:**

The relationship is significant, as the P-value is \<2e-16 (very small). In plain language, the chances that the what the data is showing us (linear relationship) is purely due to chance and not a true correlation, is incredibly small.

------------------------------------------------------------------------

### **2.3.1:**

The size (slope) of the relationship between count of paternal DNMs and paternal age is 1.35384. This means that for every additional year of paternal age, you could expect an additional 1.35384 DNMs from paternal gametes. This seems to generally match the scatter plot, as the slope is positive, and significantly more steep than the maternal plot.

------------------------------------------------------------------------

### **2.3.2:**

The relationship is significant, as the P-value is \<2e-16 (very small). In plain language, the chances that the what the data is showing us (linear relationship) is purely due to chance and not a true correlation, is incredibly small.

------------------------------------------------------------------------

### **Step 2.4 — Predict for a 50.5-year-old father**

``` text
y = 1.35384 (50.5) + 10.32632
y = 78.69524
```

------------------------------------------------------------------------

### **Step 2.5 — Compare distributions of maternal vs. paternal DNMs**

**Test used:**

``` r
t.test(merged_data$mother, merged_data$father, paired = TRUE)
```

**Output:**

``` text
Paired t-test
data:  merged_data$mother and merged_data$father
t = -61.609, df = 395, p-value < 2.2e-16
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
  -40.48685 -37.98284

sample estimates:

mean difference 
 -39.23485 
```

------------------------------------------------------------------------

### **2.5.1:**

What is the “size” of this relationship (i.e., the average difference in counts of maternal and paternal DNMs)? Interpret the difference in plain language. Does it match your plot?

Average difference is -39.23485 which means that fathers contribute about 39 more DNMs per proband than mothers. This matches the plots, where the paternal DNM vs Father age plot has DNM counts that go almost up to 90 while the maternal plot only has a y axis that extends to about 40.

------------------------------------------------------------------------

### **2.5.2:**

Is the relationship significant? How do you know? Explain the p-value in plain but precise language.

The relationship is significant. The p value is very small. The p value represents the chance that the relationship we see between the distribution of maternal and paternal DNMs is by chance (essentially 0 in this case).

------------------------------------------------------------------------

**Code:**

``` r
lm(I(mother - father) ~ 1, data = merged_data) %>% summary()
```

**Output:**

``` text
Residuals:
   Min      1Q  Median      3Q     Max 
 -61.765  -7.765   1.235   9.235  30.235 
 
 Coefficients:
   Estimate Std. Error t value Pr(>|t|)    
 (Intercept) -39.2348     0.6368  -61.61   <2e-16 ***
 
 Residual standard error: 12.67 on 395 degrees of freedom
```

------------------------------------------------------------------------

### **How would you interpret the coefficient estimate for the intercept term?**

The intercept is -39.2348 (aligns with T test) and again can be interpreted as fathers contribute 39.2348 more DNM per proband than mothers.

------------------------------------------------------------------------

# **Ex3 - I am using the data set "Pixar Films"**

------------------------------------------------------------------------

## **Hypothesis 1:**

Film run time correlates negatively with critical reviews

### **Interpretation of plot:**

While the slope of each critical review score type does seem negative, the lines look mostly flat. I don't think this pairing is worth exploring more.

------------------------------------------------------------------------

## **Hypothesis 2:**

Film release date correlates negatively with critical reviews

### **Interpretation of plot:**

The slopes here seem much more robustly negative (though still subtle) I will test this relationship with a linear regression

------------------------------------------------------------------------

### **Output:**

``` text
Call:
lm(formula = score ~ release_year, data = pixar_date_numeric)

Residuals:
    Min      1Q  Median      3Q     Max
-45.128  -6.039   2.640   8.634  16.110

Coefficients:
              Estimate Std. Error t value Pr(>|t|)
(Intercept)  1150.4366   426.7983   2.696  0.00894 **
release_year   -0.5297     0.2123  -2.495  0.01513 *

Residual standard error: 12.19 on 65 degrees of freedom
Multiple R-squared:  0.08743,   Adjusted R-squared:  0.07339
F-statistic: 6.227 on 1 and 65 DF,  p-value: 0.01513
```

------------------------------------------------------------------------

## **Interpretation of regression model:**

There is a small but statistically significant negative relationship between release year and review score. On average, each newer year corresponds to roughly half a point lower in review score. The model only explains about 9% (R-squared 8.743%) of the variation in scores (small effect).
